# Generated by Django 4.2.4 on 2023-10-20 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence_type', models.CharField(choices=[('LTR', 'Letter'), ('EML', 'Email'), ('PHN', 'Phonecall'), ('FAX', 'Fax')], default='Email', max_length=3)),
                ('correspondence_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correspondence_document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
