# Generated by Django 4.1.6 on 2023-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrequest',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='actionrequest',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actionrequest',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='arts-documents/'),
        ),
    ]
