# Generated by Django 4.2.6 on 2023-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrequest',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
