# Generated by Django 4.1.6 on 2023-10-21 19:15

import arts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_actionrequest_comments_alter_actionrequest_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrequest',
            name='due_date',
            field=models.DateTimeField(default=arts.models.get_default_due_date),
        ),
    ]
